# 读取input.h5文件

In [1]:
import dynclipy

# 保存/home/huang/PyCode/scRNA/PyDynverse/PyDynverse/pydynverse/wrap/method_execute.py生成的PAGA临时输入input.h5文件，目的是看看dyclipy是如何处理输入

# 参数部分
tmp_dir = "/home/huang/RCode/scrna_tools/dynverse_reproduce/dynclipy/tmp"
input_h5 = f"{tmp_dir}/input.h5"
output_h5 = f"{tmp_dir}/output.h5"
# args = f"--dataset {input_h5} --output output_h5"
args = ["--dataset", input_h5, "--output", output_h5]

# 方法描述定义部分
definition_location = "/home/huang/RCode/scrna_tools/dynverse_reproduce/ti_paga/definition.yml" 

task = dynclipy.main(args, definition_location) # 内部其实是调用了R的代码

In [8]:
for k,v in task.items():
    print(k, type(v))
task["counts"]

counts <class 'pandas.core.frame.DataFrame'>
expression <class 'str'>
parameters <class 'dict'>
priors <class 'dict'>
verbosity <class 'int'>
seed <class 'int'>
output <class 'str'>

,Acta1,Tnnc2,Myl1,Tnni1,Tnnc1,Pgam2,S100a6,Acta2,Tnnt2,Mylpf,...,Stmn3,Fam114a1,Vamp7,Zfp422,Ctsa,Lyar,Pdcl3,Bloc1s2,Tmem30a,Hmgb3
1_iN1_C01,0,0,33.903669,0,0,153.981572,161.117224,0,0,0,...,0,0,0,0,67.133772,0,161.224852,0,2.471815,212.995224
1_iN1_C02,0,0,0,0,498.489294,1229.91581,747.442796,27.039307,87.745662,0,...,0,3.393281,97.324545,72.484644,41.092829,4.217834,7.02325,0,0,28.450226
1_iN1_C03,0,0,0,2.120709,0,74.141266,110.662463,0.110043,359.400937,0,...,0,0,0,0,42.122793,0,2.492618,15.217326,18.333119,4.517833
1_iN1_C04,0.049921,0,0,0,21.808033,0,10448.372748,1368.995901,0,0,...,0,108.072124,0,0,39.011875,35.326484,166.623397,0,0,0
1_iN1_C05,0,0,0,0,81.258883,49.721842,1157.49181,664.525128,2.027764,0,...,0,89.941017,1.746886,8.264864,36.203476,24.103494,100.623659,6.245773,0,3.248844
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
714_507_1g_22d1_C60,19377.845055,12151.745596,16142.665081,7221.853037,6264.353561,2798.597325,0,0,1167.195705,2946.510276,...,0,0.429584,47.651821,0,15.233142,0,28.110655,43.731107,2.512778,0
714_508_1g_22d1_C72,2591.063373,3542.530514,8.084785,136.132999,5.964247,3325.780676,0,0,794.56613,0,...,0,35.328316,0,0,0,1.074828,0,24.634907,210.46374,0
715_506_1gg_22d2_C72,3337.491319,2388.55369,2755.869836,2373.199309,1230.794432,5419.045151,0,0,369.715021,61.021653,...,0,17.780007,33.906514,0,3.522675,0,33.947719,118.474097,44.758207,0
715_507_1gg_22d2_C76,3779.933548,6054.501654,24764.500598,1370.144538,790.255683,1282.500591,0,0,215.924206,716.697333,...,0,0,77.64348,0,7.364678,0.561079,70.677542,31.474045,0.277555,0
715_508_1n_22d1_C70,7.046496,5.076549,1.928182,0.028402,0,0,171.552924,0,0,0,...,0,0,0,0,572.958728,0,0,34.540498,5.682274,0

In [10]:
task["expression"]

'counts'

思考一下，看看main函数，为什么自动转化为Python可识别的字典格式呢？这是因为__init__里有关于R和Python数据转化的定义， 以及read和write里一堆装饰器定义数据转换的作用

```
from rpy2.robjects import pandas2ri
pandas2ri.activate()

from rpy2.robjects import numpy2ri
numpy2ri.activate()

```